- app/assets/stylesheets/pages/_banner.scss
- app/assets/stylesheets/pages/_button.scss
- app/assets/stylesheets/pages/_card.scss
- app/assets/stylesheets/pages/_footer.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_navbar.scss
- app/assets/stylesheets/pages/_search.scss
- app/views/layouts/application.html.erb
- app/views/pages/_banner.html.erb
- app/views/pages/_card.html.erb
- app/views/pages/_footer.html.erb
- app/views/pages/_navbar.html.erb
- app/views/pages/_search.html.erb
- app/views/pages/home.html.erb
i just added some basic elements to the front end of the index page
created some partials element in html and css
> added some elements to the home page

- app/assets/stylesheets/pages/_banner.scss
- app/assets/stylesheets/pages/_footer.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_navbar.scss
- app/views/pages/_banner.html.erb
- app/views/pages/_card.html.erb
- app/views/pages/_footer.html.erb
- app/views/pages/_navbar.html.erb
- app/views/pages/home.html.erb
> Frontend extended

- app/controllers/pages_controller.rb
- app/controllers/reviews_controller.rb
- config/routes.rb
added reviews controller
added the pages controller
added destroy to reviews routes in routes.rb
> added the reviews and pages controller

- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/index.html.erb
- app/views/events/new.html.erb
Worked on Events: added methods and created views, adding forms.
> Work on Events Controller and Views

- app/assets/stylesheets/pages/_show.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/pages/show.html.erb
> Create show.html.erb  and show.scss

- app/controllers/categories_controller.rb
- app/controllers/events_controller.rb
- app/models/event.rb
- app/views/events/new.html.erb
- app/views/events/show.html.erb
Now able to create events and display them.
> Worked on Events controller

- app/assets/stylesheets/pages/_search.scss
- app/controllers/pages_controller.rb
- app/models/booking.rb
- app/models/user.rb
- app/views/pages/_banner.html.erb
- app/views/pages/_card.html.erb
- app/views/pages/_search.html.erb
- app/views/pages/home.html.erb
- db/seeds.rb
changed seed, some models, controller, view, and index
> seed + index

- app/assets/stylesheets/pages/_card.scss
- app/assets/stylesheets/pages/_footer.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/events/show.html.erb
- app/views/pages/_footer.html.erb
- app/views/pages/home.html.erb
- db/seeds.rb
modified index page and made cards dynamics
created events
modified footer
> changed the view and made it dynamic

- app/views/bookings/_new.html.erb
- app/views/events/show.html.erb
Fixed the booking button. 
Booking creation still works.
> Fixed Booking button

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/events/_button.scss
- app/assets/stylesheets/events/_index.scss
- app/views/events/index.html.erb
Events page now unstuck (removed image url, to be re-added later).
> Unstuck the Events page

- app/views/layouts/application.html.erb
Removed alerts for now. Can be put on later at the bottom left corner of the page.
> Removed alerts

- Gemfile
- Gemfile.lock
- config/initializers/geocoder.rb
Installed the geocoder gem. 
Run "bundle install" after pulling from master.
> Installed geocoder gem

- app/models/event.rb
- db/migrate/20220602062410_add_coordinates_to_events.rb
- db/schema.rb
Please run "bundle install" and "rails db:migrate" after pulling from master.
> Added longitude and latitude to Events table

- app/controllers/events_controller.rb
- app/javascript/controllers/mapbox_controller.js
- app/views/pages/home.html.erb
> work work work

- app/controllers/reviews_controller.rb
- app/models/booking.rb
- app/models/event.rb
- app/models/review.rb
- app/views/events/show.html.erb
- config/routes.rb
worked on the review section in show
modified routes, review model, review controller, booking model, routes and event show
> worked on review

- app/controllers/pages_controller.rb
- app/javascript/controllers/mapbox_controller.js
- app/views/events/index.html.erb
Fixed markers not showing up. Added @markers to PagesController.
> Fixed wonky map

- app/controllers/events_controller.rb
- app/views/events/show.html.erb
Added event marker on event page
> Added event marker on event page

- app/controllers/events_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/users_controller.rb
- app/views/pages/_navbar.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- test/controllers/users_controller_test.rb
Added user profile page. Added condition where the link is only shown when logged in.
> Added user page

- app/views/users/show.html.erb
added the display for user profile account
> added profile show

- app/controllers/events_controller.rb
- app/controllers/pages_controller.rb
> search fix

- app/views/pages/_navbar.html.erb
adjusted search bar in nav bar
> adjusted nav bar search feature

- app/controllers/bookings_controller.rb
Booking leads to user page after save
> Booking leads to user page after save

- app/models/review.rb
- app/views/pages/_banner.html.erb
> Some tweaks
